.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. emircoin_qt test_emircoin_qt
clean: FORCE
	$(MAKE) -C .. emircoin_qt_clean test_emircoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_emircoin_qt_check
emircoin-qt emircoin-qt.exe: FORCE
	 $(MAKE) -C .. emircoin_qt
